### ISSUE TITLE
YSFlight 20181124 released

### ISSUE THREAD

**Issue by Symbian9** [YSFHQ/marketing#10]
Soji Yamakava finally released new stable YSFlight

![pic.1](https://i.imgur.com/GVKaYZo.png)

Currently there are NO official ~~announcement~~ release notes yet

- http://ysflight.in.coocan.jp/ysflight/ysflight/e.html

And only *Windows* installer available at this moment:

- https://download.cnet.com/YS-Flight-Simulator/3000-2115_4-10114866.html?part=dl-&subj=dl&tag=button

@EricTendian, add this installer downloads archive, please:

-  http://ysflight.org/download

I hope that Soji will upload installers for Linux and Mac in next few days and will publish official announcement.

**Comment by Symbian9** [comment]
@EricTendian, binary for *YSFlight 20181124* (RELEASE) finally uploaded

- for Windows (~ 14 MB) - http://ftp.vector.co.jp/71/09/3482/YsflightForWindows.zip
- for macOS & Linux (~ 55 MB) - http://ftp.vector.co.jp/71/09/822/YsflightForMacOSX.zip

Please, add them into archive.

**Comment by EricTendian** [comment]
@Symbian9 thank you! Site updated with new stable version.
