### ISSUE TITLE
1st version of YSFlight is 19990515 (not 19990415)

### ISSUE THREAD

**Issue by Symbian9** [YSFHQ/marketing#11]
According Soji's notes 1st version is 19990515

- http://ysflight.in.coocan.jp/ysflight/ysflight/e.html
 
> On May 14, 1999, I finally overcame my biggest challenge and passed the Ph.D Qualifying Exam. And, I released the first version of YSFLIGHT. I don't remember exact date when I released the first version, but the time stamps of the files included in the first-version archive implies that it was May 15, 1999.
> 
> - http://ysflight.in.coocan.jp/ysflight/ysflight/ysfs-1stversion.zip

Inside original `ysfs-1stversion.zip` all files also dated on 19990515:

![pic.1](https://i.imgur.com/zXQeElG.png)

On YSFHQ Archive info is incorrect:

> YSFlight.org is the only place to find *every* past version of YSFlight going back to April 15, 1999.
>
> | Version | Release Date | Download Link |
> | :---: | :---: | :---: |
> | 19990415 | April 15, 1999 | [Windows](https://ysflight.org/files/19990415YsflightForWindows.zip) |

So, need rename `19990415YsflightForWindows.zip`, currently stored in YSFHQ archive, into `19990515YsflightForWindows.zip` and correct info in table

> YSFlight.org is the only place to find *every* past version of YSFlight going back to May 15, 1999.
>
> | Version | Release Date | Download Link |
> | :---: | :---: | :---: |
> | 19990515 | May 15, 1999 | [Windows](https://ysflight.org/files/19990515YsflightForWindows.zip) |

P.S.: *20th Anniversary of YSFLIGHT*

- https://forum.ysfhq.com/viewtopic.php?f=137&t=10190

**Comment by EricTendian** [comment]
Good catch. Fixed.
