### ISSUE TITLE
Update "DOWNLOAD" section

### ISSUE THREAD

**Issue by u2fly** [YSFHQ/marketing#2]
Update list of YSFlight releases.
* https://ysflight.org/download/

Currently latest listed version is "YSFlight 20110207 RC" (February 7, 2011)

Many users after reading this list think that there no updates after 2011, but here are newest releases
## YSFLIGHT releases (after 2011)
* http://ysflight.in.coocan.jp/ysflight/ysflight/e.html
  * [ ] "**YSFLIGHT 20120701**"
    * [x] for Linux - http://www.mediafire.com/download/a4vxcv9m8rtm63w/ysflight-linux.zip
    * [x] for Windows - https://www.mediafire.com/file/xaxk6g1un8r0g38/YsflightForWindows_%281%29.zip
    * [ ] for MacOS X - (not found yet)
  * [ ] "**YSFLIGHT 20130805**"
    * [ ] for Linux - (not found yet)
    * [x] for Windows - https://drive.google.com/uc?export=download&id=0B-Ok3pCisiEMcWtWRmhTSExaYUE
    * [x] for MacOS X - https://www.mediafire.com/?oza877tyy97471m
  * [x] "**YSFLIGHT 20150425**"
    * [x] for Linux - http://web.archive.org/web/20170524032344/http://ysflight.in.coocan.jp/download/YsflightForLinux.zip
    * [x] for Windows - http://web.archive.org/web/20170604043639/http://ftp.vector.co.jp/65/24/3482/YsflightForWindows.zip
    * [x] for MacOS X - http://web.archive.org/web/20170524204149/http://ysflight.in.coocan.jp/download/YsflightForMacOSX_R5165.zip

**Comment by u2fly** [comment]
Can't find by myself "YSFlight for Linux 20130805" and "YSFlight for MacOS X 20120701". Need help with those two builds.

**Comment by EricTendian** [comment]
Closing this as it's mostly fixed, pending a few really old builds from Soji.
