### ISSUE TITLE
"ysfhq.com/download" redirect to "404"

### ISSUE THREAD

**Issue by u2fly** [YSFHQ/marketing#3]
If now try open this page...
* https://ysfhq.com/downloads.html

... then it redirect to "404" page. Here is snapshot:
* http://web.archive.org/web/20170604141146/https://ysfhq.com/downloads.html

REFERENCE:
* https://forum.ysfhq.com/ucp.php?i=pm&mode=compose&mchat_pm_quote_message=44806&u=543

**Comment by EricTendian** [comment]
Added the page from the Wayback Machine and updated the links.
