### ISSUE TITLE
"YSFlight 20171217 Test" out (2017/12/22)

### ISSUE THREAD

**Issue by Symbian9** [YSFHQ/marketing#4]
Builds:
- macOS & Linux - http://ysflight.in.coocan.jp/download/YsflightForMacOSX-test-20171222.zip
- Windows - http://ysflight.in.coocan.jp/download/YsflightForWindows-test-20171222.zip

Soji Yamakawa wrote:
> 2017/12/22
> - Bug fix:  Change of "Default Field" in the config dialog was not updating the starting points.
> - Bug fix:  "NO CLOUD" option was ignored.
> - Bug fix:  Full-Screen setting was ignored after restart.
> - Bug fix:  Fly-Heading-Bug auto pilot was ignoring magnetic variation.
> - Bug fix:  ATC's heading instruction was ignoring magnetic variation. (I think I fix it. Hope I didn't break it.)
> - Bug fix:  Starting-Position search text box in New-Flight Dialog was not functioning. Selection changes, but not really selected.
> - Bug fix:  Aircraft DNM not initialized in the aircraft-selection dialog.
> - Racing Mode (Still in the middle of making)
> - Implemented Endurance Mode, Intercept Mission, Ground-to-Air Mission, Close-Air-Support Mission as an extension.  The first goal is to reduce the running modes of the program into 5 modes: GUI, Flying, Replay, Server, and Client.  Those missions used to be an independent mode, which was making the program very difficult to maintain. Eventually I want to make Server and Client as an extension, but that's the next stage.
> 
> I learned a lot about C++ programming through YSFLIGHT. That means in many places, I learned a better practice, which improved my research / work code, but it was too late for YSFLIGHT. Also known as code debt. I am cleaning those mess.
> 
> With this change, I still have three additional modes to turn into an extension. So, if you can help me debugging it, I'll appreciate if you can fly a few times of those missions.

@EricTendian, please update it in downloads too
- http://ysflight.org/download

**Comment by EricTendian** [comment]
Thanks! I have updated the downloads.

**Comment by Symbian9** [comment]
For the record, this is "YSFlight 20171217 Test", NOT 20171222.
