### ISSUE TITLE
"YSFlight 20180314 Unstable" & "SceneryEditor 20180314 Unstable" out

### ISSUE THREAD

**Issue by Symbian9** [YSFHQ/marketing#5]
SOURCE - http://ysflight.in.coocan.jp/ysflight/ysflight/testvere.html

YSFlight:

- for Linux & macOS - http://ysflight.in.coocan.jp/download/YsflightForMacOSX-test-20180314.zip
- for Windows - http://ysflight.in.coocan.jp/download/YsflightForWindows-test-20180314.zip

SceneryEditor:

- for Linux - http://ysflight.in.coocan.jp/download/ScnEditForLinux-test-20180314.zip
- for macOS - http://ysflight.in.coocan.jp/download/ScnEditForMacOSX-test-20180314.zip
- for Windows - http://ysflight.in.coocan.jp/download/ScnEditForWindows-test-20180314.zip

*Soji Yamakawa* wrote:

> 2018/03/14
> 
> - Can put SRF models in FLD. (Can be done from the Scenery Editor). Very long time ago, FLD had this feature but the collision was checked against the bounding box. In this update, the collision is checked per polygon. I really wanted to add field-specific ground object, but anyway SRF in FLD is also needed for complex terrain.
> - Bug fix: If a DNM model defines rotation based on STATE 0, new data structure was not transforming it as intended. Sorry, I was not clear about which of no-transformation or STATE-0 is the base orientation. I was thinking to make it no-transformation, but looks like there are many models that are assuming STATE-0 is the base. I'm leaning toward making STATE-0 as the base orientation.
> - Bug fix: Fireball renderer was not clearing Emissive color in D3D9 code.
> - I'm also experimenting with unit-test scripts. So far I was able to automate selecting all items in Simulation menu, selecting all default fields, and some config items. I need to automate testing file menus and network features.

@EricTendian, please update downloads archive

- http://ysflight.org/download

**Comment by EricTendian** [comment]
Thanks for the notification! Just updated the download page.
