### ISSUE TITLE
YSFlight 20180519 Test

### ISSUE THREAD

**Issue by Symbian9** [YSFHQ/marketing#7]
*Soji Yamakawa* wrote:

> - http://ysflight.in.coocan.jp/ysflight/ysflight/testvere.html
> 
> **2018/05/19**
> 
> - I think this time I really fixed the magnetic heading and true heading consistency.  By the way, I made the sign back to the previous.  (In YSFLIGHT West is positive.)
> - ARTCC was not giving higher than 10000ft, which was awkward for a long cross country in a jet airplane.  Now it gives up to the altitude specified in the aircraft data.  (Actually, the descending instruction was supposed to be given +6000, +3000, and then +1500 of the destination airport, but for some reason the current ATC skips +3000.  I'm looking into the problem.)

@EricTendian, update downloads archive, please:

- http://ysflight.org/download

### DOWNLOAD

- for Linux & macOS - http://ysflight.in.coocan.jp/download/YsflightForMacOSX-test-20180519.zip
- for Windows - http://ysflight.in.coocan.jp/download/YsflightForWindows-test-20180519.zip

**Comment by EricTendian** [comment]
Added the new version to the archive.
