### ISSUE TITLE
YSFlight 20180704 Test & SceneryEditor 20180704 Test

### ISSUE THREAD

**Issue by Symbian9** [YSFHQ/marketing#8]
*Soji Yamakawa* wrote:

> - http://ysflight.in.coocan.jp/ysflight/ysflight/testvere.html
> 
> **2018/07/04**
> 
> - I'm thinking to start pre-release test based on this version.
> - Fixed VOR OBS indication. (I should make a Pittsburgh map so that I can positively check heading/OBS indications...)
> - Scenery Editor: Prevent Color-Palette Dialog disappearance.

@EricTendian, update downloads archive, please:

- http://ysflight.org/download

### DOWNLOAD

- YSFlight (for Windows) — http://ysflight.in.coocan.jp/download/YsflightForWindows-test-20180704.zip
- YSFlight (for Linux & MacOS) — http://ysflight.in.coocan.jp/download/YsflightForMacOSX-test-20180704.zip
- SceneryEditor (for Windows) — http://ysflight.in.coocan.jp/download/ScnEditForWindows-test-20180704.zip
- SceneryEditor (for MacOS) — http://ysflight.in.coocan.jp/download/ScnEditForMacOSX-test-20180704.zip
- SceneryEditor (for Linux) — http://ysflight.in.coocan.jp/download/ScnEditForLinux-test-20180704.zip

**Comment by EricTendian** [comment]
Updated.
