### ISSUE TITLE
YSFlight 20181001 Test Version (pre-release)

### ISSUE THREAD

**Issue by Symbian9** [YSFHQ/marketing#9]
Soji Yamakawa wrote:

> 2018/10/01
>
> - Corrected OpenGL 2.0/ES 2.0 rendering error.
> - Support macOS 10.14. Actually I had to make more-than-expected corrections in user-interface. Please let me know if you find some strange behavior in the UI.

DOWNLOAD:

- for Windows — http://ysflight.in.coocan.jp/download/YsflightForWindows-test-20181001.zip
- for MacOS and Linux — http://ysflight.in.coocan.jp/download/YsflightForMacOSX-test-20181001.zip

@EricTendian, update downloads archive, please:

- http://ysflight.org/download

> ***NOTE:*** This version look like last test version before upcoming release, so, please, report to Soji Yamakawa all bugs that You already found in test versions during period 2017-2018 and still not fixed in 20181001 Test Version!

**Comment by EricTendian** [comment]
Thanks, updated.
